Controllers/StudentController.cs
using Task1.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Task1.Controllers
{
    public class StudentController : Controller
    {
        private readonly CipherFormContext _context;
        private readonly IWebHostEnvironment enve;

        public StudentController(CipherFormContext context, IWebHostEnvironment enve)
        {
            _context = context;
            this.enve = enve;
        }


        [HttpGet]
        public IActionResult StudentCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> StudentCreate(StudentViewModal student)
        {
            string fileName = "";
            if (student.Photo != null)
            {
                var ext = Path.GetExtension(student.Photo.FileName);
                var size = student.Photo.Length;
                if (ext.Equals(".png") || ext.Equals(".jpg") || ext.Equals(".jpeg") && size <= 500000)
                {


                    string folder = Path.Combine(enve.WebRootPath, "StudentImage");
                    fileName = Guid.NewGuid().ToString() + "_" + student.Photo.FileName;
                    string filepath = Path.Combine(folder, fileName);

                    student.Photo.CopyTo(new FileStream(filepath, FileMode.Create));

                    Student obj = new Student();
                    {
                        obj.StudentName = student.StudentName;
                        obj.Age = student.Age;
                        obj.Class = student.Class;
                        obj.RollNumber = student.RollNumber;
                        obj.Image = fileName;

                    };
                    _context.Students.Add(obj);
                    _context.SaveChanges();
                    TempData["Success"] = "Student Details Successfully";
                    return RedirectToAction("ListofStudent");
                }




                else
                {
                    TempData["Ext_Error"] = "Only jpg npj.ejpg allow";
                }
               

            }

            return View(student);
        }

        public IActionResult ListofStudent()
        {
            return View(_context.Students.ToList());
        }
    }
}

Controllers/SubjectTeacherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task1.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Task1.Controllers
{
    public class SubjectTeacherController : Controller
    {
        private readonly CipherFormContext _context;

        public SubjectTeacherController(CipherFormContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> SubjectTeacher()
        {
            var subjectTeachers = await _context.SubjectTeachers
             .Include(st => st.Subject)
             .Include(st => st.Teacher)
             .ToListAsync();

            return View(subjectTeachers);
        }
        }
    }

Controllers/SubjectsController.cs
using Task1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;



namespace Develpertask1.Controllers
{
    public class SubjectsController : Controller
    {

        private readonly CipherFormContext _context;

        public SubjectsController(CipherFormContext context)
        {
            _context = context;
        }

       
        [HttpGet]
        public IActionResult SubCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SubCreate(Subject subject)
        {
            if (ModelState.IsValid)
            {
                _context.Subjects.Add(subject);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Subject Details Submit Successfully";
            }
            return View(subject);
        }

        public IActionResult SubjectTable()
        {
            return View(_context.Subjects.ToList());
        }

    }
}

Controllers/TeacherController.cs
using Task1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace Develpertask1.Controllers
{
    public class TeacherController : Controller
    {
        private readonly CipherFormContext _context;
        
        private readonly IWebHostEnvironment enve;
        public TeacherController(CipherFormContext context, IWebHostEnvironment enve)
        {

            _context = context;
            this.enve = enve;
        }

        
        [HttpGet]
        public IActionResult TeacherCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> TeacherCreate(TeacherViewModal teacher)
        {
            string fileName = "";
            if (teacher.Photo != null)
            {
                var ext = Path.GetExtension(teacher.Photo.FileName);
                var size = teacher.Photo.Length;
                if (ext.Equals(".png") || ext.Equals(".jpg") || ext.Equals(".jpeg") && size <= 500000)
                {


                    string folder = Path.Combine(enve.WebRootPath, "TeacherImage");
                    fileName = Guid.NewGuid().ToString() + "_" + teacher.Photo.FileName;
                    string filepath = Path.Combine(folder, fileName);

                    teacher.Photo.CopyTo(new FileStream(filepath, FileMode.Create));

                    Teacher obj = new Teacher();
                    {
                        obj.TeacherName = teacher.TeacherName;
                        obj.Age = teacher.Age;
                       
                        obj.Gender = teacher.Gender;
                        obj.Image = fileName;

                    };
                    _context.Teachers.Add(obj);
                    _context.SaveChanges();
                    TempData["Success"] = "Student Details Successfully";
                    //return RedirectToAction("ListofStudent");
                }




                else
                {
                    TempData["Ext_Error"] = "Only jpg npj.ejpg allow";
                }


            }

            return View();


        }

        public IActionResult TeacherTable()
        {
            return View(_context.Teachers.ToList());
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Task1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="ListofStudent">ListofStudent</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="StudentCreate">StudentCreate</a>
                        </li>
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="TeacherCreate">TeacherCreate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="TeacherTable">TeacherTable</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="SubCreate">SubCreate</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="SubjectTable">SubjectTable</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SubjectTeacher" asp-action="SubjectTeacher">SubjectTeacher</a>
                        </li>

                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src=" https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
    <script src=" https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap5.js"></script>


    <script>
        $(document).ready(function () {
            $('#datatable').DataTable({
               
            });
        });
    </script>


</body>
</html>